# Generated by Django 2.0.1 on 2018-05-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=50)),
                ('header_parameter', models.TextField()),
                ('content_parameter', models.TextField()),
                ('tk_parameter', models.CharField(max_length=40)),
            ],
        ),
    ]
