# Generated by Django 2.0.1 on 2018-05-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_eg',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('case_name', models.CharField(max_length=50)),
                ('header_parameter', models.TextField()),
                ('content_parameter', models.TextField()),
                ('tk_parameter', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='case',
        ),
    ]
