# Generated by Django 2.0.1 on 2018-06-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntest', '0002_auto_20180516_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('env_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('env_name', models.TextField()),
            ],
        ),
    ]
